/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as SpelRouteImport } from './routes/spel'
import { Route as SpelIndexRouteImport } from './routes/spel.index'
import { Route as SpelPlanningRouteImport } from './routes/spel.planning'
import { Route as SpelRapportRouteImport } from './routes/spel.rapport'
import { Route as SpelRugzakRouteImport } from './routes/spel.rugzak'
import { Route as SpelSchoolRouteImport } from './routes/spel.school'
import { Route as SpelToetsRouteImport } from './routes/spel.toets'
import { Route as SpelVaardighedenRouteImport } from './routes/spel.vaardigheden'
import { Route as SpelVoortgangRouteImport } from './routes/spel.voortgang'
import { Route as SpelHuiswerkIndexRouteImport } from './routes/spel.huiswerk.index'
import { Route as SpelHuiswerkIdRouteImport } from './routes/spel.huiswerk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelRoute = SpelRouteImport.update({
  id: '/spel',
  path: '/spel',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelIndexRoute = SpelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpelRoute,
} as any)
const SpelPlanningRoute = SpelPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => SpelRoute,
} as any)
const SpelRapportRoute = SpelRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => SpelRoute,
} as any)
const SpelRugzakRoute = SpelRugzakRouteImport.update({
  id: '/rugzak',
  path: '/rugzak',
  getParentRoute: () => SpelRoute,
} as any)
const SpelSchoolRoute = SpelSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => SpelRoute,
} as any)
const SpelToetsRoute = SpelToetsRouteImport.update({
  id: '/toets',
  path: '/toets',
  getParentRoute: () => SpelRoute,
} as any)
const SpelVaardighedenRoute = SpelVaardighedenRouteImport.update({
  id: '/vaardigheden',
  path: '/vaardigheden',
  getParentRoute: () => SpelRoute,
} as any)
const SpelVoortgangRoute = SpelVoortgangRouteImport.update({
  id: '/voortgang',
  path: '/voortgang',
  getParentRoute: () => SpelRoute,
} as any)
const SpelHuiswerkIndexRoute = SpelHuiswerkIndexRouteImport.update({
  id: '/huiswerk/',
  path: '/huiswerk/',
  getParentRoute: () => SpelRoute,
} as any)
const SpelHuiswerkIdRoute = SpelHuiswerkIdRouteImport.update({
  id: '/huiswerk/$id',
  path: '/huiswerk/$id',
  getParentRoute: () => SpelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profiel': typeof ProfielRoute
  '/spel': typeof SpelRouteWithChildren
  '/spel/planning': typeof SpelPlanningRoute
  '/spel/rapport': typeof SpelRapportRoute
  '/spel/rugzak': typeof SpelRugzakRoute
  '/spel/school': typeof SpelSchoolRoute
  '/spel/toets': typeof SpelToetsRoute
  '/spel/vaardigheden': typeof SpelVaardighedenRoute
  '/spel/voortgang': typeof SpelVoortgangRoute
  '/spel/': typeof SpelIndexRoute
  '/spel/huiswerk/$id': typeof SpelHuiswerkIdRoute
  '/spel/huiswerk/': typeof SpelHuiswerkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiel': typeof ProfielRoute
  '/spel/planning': typeof SpelPlanningRoute
  '/spel/rapport': typeof SpelRapportRoute
  '/spel/rugzak': typeof SpelRugzakRoute
  '/spel/school': typeof SpelSchoolRoute
  '/spel/toets': typeof SpelToetsRoute
  '/spel/vaardigheden': typeof SpelVaardighedenRoute
  '/spel/voortgang': typeof SpelVoortgangRoute
  '/spel': typeof SpelIndexRoute
  '/spel/huiswerk/$id': typeof SpelHuiswerkIdRoute
  '/spel/huiswerk': typeof SpelHuiswerkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profiel': typeof ProfielRoute
  '/spel': typeof SpelRouteWithChildren
  '/spel/planning': typeof SpelPlanningRoute
  '/spel/rapport': typeof SpelRapportRoute
  '/spel/rugzak': typeof SpelRugzakRoute
  '/spel/school': typeof SpelSchoolRoute
  '/spel/toets': typeof SpelToetsRoute
  '/spel/vaardigheden': typeof SpelVaardighedenRoute
  '/spel/voortgang': typeof SpelVoortgangRoute
  '/spel/': typeof SpelIndexRoute
  '/spel/huiswerk/$id': typeof SpelHuiswerkIdRoute
  '/spel/huiswerk/': typeof SpelHuiswerkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profiel'
    | '/spel'
    | '/spel/planning'
    | '/spel/rapport'
    | '/spel/rugzak'
    | '/spel/school'
    | '/spel/toets'
    | '/spel/vaardigheden'
    | '/spel/voortgang'
    | '/spel/'
    | '/spel/huiswerk/$id'
    | '/spel/huiswerk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profiel'
    | '/spel/planning'
    | '/spel/rapport'
    | '/spel/rugzak'
    | '/spel/school'
    | '/spel/toets'
    | '/spel/vaardigheden'
    | '/spel/voortgang'
    | '/spel'
    | '/spel/huiswerk/$id'
    | '/spel/huiswerk'
  id:
    | '__root__'
    | '/'
    | '/profiel'
    | '/spel'
    | '/spel/planning'
    | '/spel/rapport'
    | '/spel/rugzak'
    | '/spel/school'
    | '/spel/toets'
    | '/spel/vaardigheden'
    | '/spel/voortgang'
    | '/spel/'
    | '/spel/huiswerk/$id'
    | '/spel/huiswerk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfielRoute: typeof ProfielRoute
  SpelRoute: typeof SpelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spel': {
      id: '/spel'
      path: '/spel'
      fullPath: '/spel'
      preLoaderRoute: typeof SpelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spel/': {
      id: '/spel/'
      path: '/'
      fullPath: '/spel/'
      preLoaderRoute: typeof SpelIndexRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/planning': {
      id: '/spel/planning'
      path: '/planning'
      fullPath: '/spel/planning'
      preLoaderRoute: typeof SpelPlanningRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/rapport': {
      id: '/spel/rapport'
      path: '/rapport'
      fullPath: '/spel/rapport'
      preLoaderRoute: typeof SpelRapportRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/rugzak': {
      id: '/spel/rugzak'
      path: '/rugzak'
      fullPath: '/spel/rugzak'
      preLoaderRoute: typeof SpelRugzakRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/school': {
      id: '/spel/school'
      path: '/school'
      fullPath: '/spel/school'
      preLoaderRoute: typeof SpelSchoolRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/toets': {
      id: '/spel/toets'
      path: '/toets'
      fullPath: '/spel/toets'
      preLoaderRoute: typeof SpelToetsRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/vaardigheden': {
      id: '/spel/vaardigheden'
      path: '/vaardigheden'
      fullPath: '/spel/vaardigheden'
      preLoaderRoute: typeof SpelVaardighedenRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/voortgang': {
      id: '/spel/voortgang'
      path: '/voortgang'
      fullPath: '/spel/voortgang'
      preLoaderRoute: typeof SpelVoortgangRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/huiswerk/': {
      id: '/spel/huiswerk/'
      path: '/huiswerk'
      fullPath: '/spel/huiswerk/'
      preLoaderRoute: typeof SpelHuiswerkIndexRouteImport
      parentRoute: typeof SpelRoute
    }
    '/spel/huiswerk/$id': {
      id: '/spel/huiswerk/$id'
      path: '/huiswerk/$id'
      fullPath: '/spel/huiswerk/$id'
      preLoaderRoute: typeof SpelHuiswerkIdRouteImport
      parentRoute: typeof SpelRoute
    }
  }
}

interface SpelRouteChildren {
  SpelPlanningRoute: typeof SpelPlanningRoute
  SpelRapportRoute: typeof SpelRapportRoute
  SpelRugzakRoute: typeof SpelRugzakRoute
  SpelSchoolRoute: typeof SpelSchoolRoute
  SpelToetsRoute: typeof SpelToetsRoute
  SpelVaardighedenRoute: typeof SpelVaardighedenRoute
  SpelVoortgangRoute: typeof SpelVoortgangRoute
  SpelIndexRoute: typeof SpelIndexRoute
  SpelHuiswerkIdRoute: typeof SpelHuiswerkIdRoute
  SpelHuiswerkIndexRoute: typeof SpelHuiswerkIndexRoute
}

const SpelRouteChildren: SpelRouteChildren = {
  SpelPlanningRoute: SpelPlanningRoute,
  SpelRapportRoute: SpelRapportRoute,
  SpelRugzakRoute: SpelRugzakRoute,
  SpelSchoolRoute: SpelSchoolRoute,
  SpelToetsRoute: SpelToetsRoute,
  SpelVaardighedenRoute: SpelVaardighedenRoute,
  SpelVoortgangRoute: SpelVoortgangRoute,
  SpelIndexRoute: SpelIndexRoute,
  SpelHuiswerkIdRoute: SpelHuiswerkIdRoute,
  SpelHuiswerkIndexRoute: SpelHuiswerkIndexRoute,
}

const SpelRouteWithChildren = SpelRoute._addFileChildren(SpelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfielRoute: ProfielRoute,
  SpelRoute: SpelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
